// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_attr_for_setting_freelanceConfirm_table_Offer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_attr_for_setting_freelanceConfirm_table_Offer));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111234325_changed_attr_for_setting_freelanceConfirm_table_Offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
