// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_attr_for_dbo_Profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_attr_for_dbo_Profile));
        
        string IMigrationMetadata.Id
        {
            get { return "201703280629496_change_attr_for_dbo_Profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
