// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customazing_User_added_setting_UserSurname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customazing_User_added_setting_UserSurname));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200826391_customazing_User_added_setting_UserSurname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
