// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_name_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_name_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201703301432395_Change_name_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
