// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renamed_property_UserName_to_UserLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamed_property_UserName_to_UserLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210752321_renamed_property_UserName_to_UserLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
