// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customazing_identity_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customazing_identity_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200846083_customazing_identity_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
