// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_navi_setting_bettwean_Profile_and_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_navi_setting_bettwean_Profile_and_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251504285_Added_navi_setting_bettwean_Profile_and_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
