// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_added_tbs_user_role_claim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_added_tbs_user_role_claim));
        
        string IMigrationMetadata.Id
        {
            get { return "201704222102555_initial_added_tbs_user_role_claim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
