// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201703211248459_added_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
