// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_new_property_UserFirstName_into_table_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_new_property_UserFirstName_into_table_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210801547_added_new_property_UserFirstName_into_table_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
